Repository ITA-Dnipro/PyDataCenter5000, pull requests merged in 2025-06, with the labels that each got.

#76 Create and test agent script for smtp server
  agents/agent.py
  agents/dev/__init__.py
  agents/dev/run_smtp.py
  agents/smtp/smtp.py
  agents/tests/test_agent.py
  agents/web/web.py
Labels: agent

#100 99 improve logging setup in agents
  .coveragerc
  .github/workflows/agents-tests-on-pull-request.yaml
  README.md
  agents/agent.py
  agents/dns/dns.py
  agents/smtp/smtp.py
  agents/tests/test_agent.py
  agents/tests/test_web_agent.py
  agents/web/web.py
Labels: invalid, agent

#107 89 - Store Extended Metrics in the Backend
  pydata_center/monitoring/admin.py
  pydata_center/monitoring/migrations/0005_alter_commandhistory_hostname_and_more.py
  pydata_center/monitoring/models.py
  pydata_center/monitoring/serializers.py
Labels: backend

#110 Fixed bug with requirements.txt, removed test branch from yml
  .github/workflows/monitoring-tests.yml
  pydata_center/pytest.ini
  pydata_center/requirements.txt
Labels: bug

#113 112 fix agents not finding processes if searched for name is a composite of an actual name
  agents/agent.py
  agents/smtp/smtp.py
Labels: bug, invalid, agent

#115 fix: have from_config_file instantiate agent with custom log_path properly
  agents/agent.py
Labels: bug, agent

#84 Add token based api authentication
  pydata_center/monitoring/views.py
  pydata_center/pydata_center/settings.py
  pydata_center/pydata_center/urls.py
Labels: backend

#135 Hotfix dashboard: Correct table colspan in empty view
  pydata_center/monitoring/templates/monitoring/dashboard.html
Labels: bug, comm, sub-task

#137 133 hotfix make dataclass message objects in monitoring json serializable
  pydata_center/monitoring/discord.py
  pydata_center/monitoring/email.py
  pydata_center/monitoring/tests/test_api.py
  pydata_center/pydata_center/settings.py
  pydata_center/pydata_center/utils/__init__.py
  pydata_center/pydata_center/utils/encoders.py
Labels: bug, backend

#142 Implement configurable Discord alerts for successful command executions
  pydata_center/monitoring/admin.py
  pydata_center/monitoring/alerts.py
  pydata_center/monitoring/migrations/0012_commandhistory_notify_on_success.py
  pydata_center/monitoring/models.py
  pydata_center/monitoring/serializers.py
  pydata_center/monitoring/tests/test_views_alerts.py
  pydata_center/monitoring/views.py
Labels: enhancement, comm, sub-task

#148 HOTFIX: Fix Bug in Agents - Logger Falling Back to Root
  agents/agent.py
  agents/dns/config.ini
  agents/dns/dns.py
  agents/ntp/config.ini
  agents/ntp/ntp.py
  agents/smtp/config.ini
  agents/smtp/smtp.py
  agents/tests/test_agent.py
  agents/tests/test_dns_agent.py
  agents/tests/test_smtp_agent.py
  agents/tests/test_web_agent.py
  agents/web/config.ini
  agents/web/web.py
Labels: bug, agent

#147 Added maybe_restart_service() to all agents
  agents/ntp/ntp.py
  agents/smtp/smtp.py
  agents/web/web.py
Labels: bug

#140 Realize independent coverage badges for monitoring and agents #120
  .github/workflows/agents-tests-on-pull-request.yaml
  README.md
  codecov.yml
Labels: enhancement

#159 Removed unnecessary badges
  README.md
Labels: backend

#131 55 implement multithreading logic for agents using shrapnel
  .github/workflows/agents-tests-on-pull-request.yaml
  agents/.coveragerc
  agents/__init__.py
  agents/agent.py
  agents/config/__init__.py
  agents/config/logging.ini
  agents/dev/coro_command_executor.py
  agents/dev/toy_command_executor.py
  agents/dns/dns.py
  agents/exceptions.py
  agents/global.ini
  agents/ntp/ntp.py
  agents/pytest.ini
  agents/requirements.txt
  agents/scripts/environment/docker.env
  agents/scripts/install-dependencies.sh
  agents/smtp/config.ini
  agents/smtp/smtp.py
  agents/supervisor.py
  agents/tests/conftest.py
  agents/tests/integration/__init__.py
  agents/tests/integration/test_integration_supervisor.py
  agents/tests/unit/__init__.py
  agents/tests/unit/test_agent.py
  agents/tests/unit/test_helpers.py
  agents/tests/unit/test_logtools.py
  agents/tests/unit/test_retry.py
  agents/tests/unit/test_unit_dns_agent.py
  agents/tests/unit/test_unit_smtp_agent.py
  agents/tests/unit/test_unit_supervisor.py
  agents/tests/unit/test_unit_web_agent.py
  agents/utils/__init__.py
  agents/utils/helpers.py
  agents/utils/logtools.py
  agents/utils/retry.py
  agents/vagrant/common.rb
  agents/vagrant/env.rb.example
  agents/web/web.py
Labels: enhancement, task, agent

#162 129 Create background thread to check agent's critical processes
  agents/dev/critical_processes_check.py
  agents/ntp/config.ini
  agents/ntp/ntp.py
Labels: agent, sub-task

#174 Hotfix(tests): Stabilize tests in test_views_alerts.py for isolated runs
  pydata_center/monitoring/tests/test_views_alerts.py
Labels: bug, backend, sub-task
