Repository ITA-Dnipro/PyDataCenter5000, pull requests merged in 2025-05, with the labels that each got.

#22 Create server status model and run migrations
  pydata_center/monitoring/admin.py
  pydata_center/monitoring/migrations/0001_initial.py
  pydata_center/monitoring/migrations/0002_rename_service_serverstatus_servername_and_more.py
  pydata_center/monitoring/migrations/0003_rename_servername_serverstatus_server_name.py
  pydata_center/monitoring/models.py
Labels: backend

#21 4 create and test agent script
  agents/__init__.py
  agents/agent.py
  agents/logconfig/__init__.py
  agents/logconfig/logconfig.ini
  agents/requirements.txt
  agents/smtp.py
Labels: task, agent

#32 30 optimize agents reception of metadata ip uptime etc
  agents/agent.py
  agents/dns/__init__.py
  agents/dns/config.ini
  agents/dns/dns.py
  agents/smtp/__init__.py
  agents/smtp/config.ini
  agents/smtp/smtp.py
  agents/utils/__init__.py
  agents/utils/helpers.py
  agents/utils/logconfig.ini
  agents/utils/logtools.py
Labels: enhancement, agent, sub-task

#57 Build command dispatch api in django
  pydata_center/monitoring/urls.py
  pydata_center/monitoring/views.py
Labels: backend

#63 36 create and test agent script for web server
  agents/agent.py
  agents/dev/get_agent_status.py
  agents/requirements.txt
  agents/tests/test_agent.py
  agents/tests/test_web_agent.py
  agents/web/__init__.py
  agents/web/config.ini
  agents/web/web.py
  pydata_center/monitoring/admin.py
  pydata_center/monitoring/migrations/0004_commandhistory.py
  pydata_center/monitoring/models.py
  pydata_center/monitoring/serializers.py
  pydata_center/monitoring/urls.py
  pydata_center/monitoring/views.py
  vagrant/Vagrantfile.web
  vagrant/common.rb
  vagrant/env.rb.example
Labels: agent

#72 fix: code duplication
  agents/dev/get_agent_status.py
  vagrant/common.rb
Labels: bug

#66 Vagrant smtp
  vagrant/Vagrantfile.smtp
  vagrant/common.rb
  vagrant/env.rb.example
Labels: agent
